name: Build Test and Deploy EC2

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install
        run: |
          echo "Build Successful!"

      - name: Upload artifact with retention
        uses: actions/upload-artifact@v4.6.2
        with:
          name: my-artifact
          path: dist/
          retention-days: 7
