name: Deploy EC2
on:
  workflow_run:
    workflows: ["Build and Test"]
    types: 
      - completed


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Lint
        run: yarn lint